version: '3.4'

services:
  transactionhistorydb:
    image: mongo

  transactionhistory.api:
    image: ${DOCKER_REGISTRY-}transactionhistoryapi
    build:
      context: .
      dockerfile: Microservices/TransactionHistory/TransactionHistory.API/Dockerfile
      
  paymentdb:
    image: mongo

  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Microservices/Payment/Payment.API/Dockerfile

  api.gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Gateway/API.Gateway/Dockerfile
   
  rabbitmq:
    image: rabbitmq:3-management-alpine

volumes:
  mongo_data:

